#!/usr/bin/env bash
# Worktree用の開発環境セットアップスクリプト
#
# 使い方:
#   cd .claude/worktrees/<worktree-name>
#   bash scripts/setup-worktree.sh
#
# 動作:
#   - worktree名のハッシュから一意のポート番号を割り当て (50スロット)
#   - 使用中のポートを自動で回避 (frontend / backend / db すべてチェック)
#   - .env (Compose用) と frontend/.env.local (Next.js用) を生成
#   - 通常は main の backend (port 8080) を共有して使う設定にする
#   - backend / db 変更時のために main の backend/.env をコピー

set -euo pipefail

# 実行場所の確認 (worktree のルートで実行されているか)
if [ ! -f "docker-compose.yml" ]; then
  echo "Error: docker-compose.yml が見つかりません。" >&2
  echo "       worktree のルートディレクトリで実行してください。" >&2
  exit 1
fi

CURRENT_DIR="$(pwd)"
WORKTREE_NAME="$(basename "$CURRENT_DIR")"

# main repo の場所を特定 (worktree の git common dir の親)
GIT_COMMON_DIR="$(git rev-parse --git-common-dir 2>/dev/null || echo "")"
if [ -z "$GIT_COMMON_DIR" ]; then
  echo "Error: git リポジトリではありません。" >&2
  exit 1
fi
MAIN_REPO="$(cd "$GIT_COMMON_DIR/.." && pwd)"

if [ "$CURRENT_DIR" = "$MAIN_REPO" ]; then
  echo "Error: このスクリプトは worktree 用です。main では実行しないでください。" >&2
  echo "       main は通常通り 'docker compose up backend db' で起動します。" >&2
  exit 1
fi

# worktree名のSHA1ハッシュ先頭4桁(hex)から 1〜50 のスロット番号を計算
# Frontend port: 3100〜3149, Backend port: 8100〜8149, DB port: 5500〜5549
HASH_HEX="$(printf '%s' "$WORKTREE_NAME" | shasum | cut -c1-4)"
SLOT=$(( 16#${HASH_HEX} % 50 + 1 ))

# ポート衝突を検出して自動で次のスロットへ (frontend / backend / db すべて空き)
MAX_TRIES=50
TRIES=0
while [ $TRIES -lt $MAX_TRIES ]; do
  FRONTEND_PORT=$((3100 + SLOT - 1))
  BACKEND_PORT=$((8100 + SLOT - 1))
  DB_PORT=$((5500 + SLOT - 1))
  if ! lsof -iTCP:$FRONTEND_PORT -sTCP:LISTEN >/dev/null 2>&1 \
     && ! lsof -iTCP:$BACKEND_PORT -sTCP:LISTEN >/dev/null 2>&1 \
     && ! lsof -iTCP:$DB_PORT -sTCP:LISTEN >/dev/null 2>&1; then
    break
  fi
  SLOT=$(( SLOT % 50 + 1 ))
  TRIES=$((TRIES + 1))
done

if [ $TRIES -ge $MAX_TRIES ]; then
  echo "Error: 空きポートが見つかりません (3100-3149 / 8100-8149 / 5500-5549 すべて使用中)" >&2
  exit 1
fi

write_if_absent() {
  local path="$1"
  local content="$2"
  if [ -f "$path" ]; then
    echo "  skip: $path (既に存在)"
  else
    printf '%s' "$content" > "$path"
    echo "  生成: $path"
  fi
}

echo ""
echo "Worktree:      $WORKTREE_NAME"
echo "スロット:      $SLOT"
echo "Frontend port: $FRONTEND_PORT"
echo "Backend port:  $BACKEND_PORT (Mode B/C で使用)"
echo "DB port:       $DB_PORT       (Mode C で使用)"
echo ""
echo "ファイル生成:"

# 1. Compose 用の .env (worktree ルート)
#    DATABASE_URL は Mode B (Main DB共有) をデフォルトとし、Mode C 用はコメントで残す
write_if_absent "$CURRENT_DIR/.env" "\
# Auto-generated by scripts/setup-worktree.sh
# Worktree: $WORKTREE_NAME
BACKEND_PORT=$BACKEND_PORT
DB_PORT=$DB_PORT
# Mode B (Main DB共有): デフォルト
DATABASE_URL=postgres://user:password@host.docker.internal:5433/hotaruika_db?sslmode=disable
# Mode C (Worktree DB) を使う場合は上をコメントアウトし、以下を有効化
# DATABASE_URL=postgres://user:password@db:5432/hotaruika_db?sslmode=disable
"

# 2. Next.js 用の .env.local
#    デフォルトは Mode A (Main backend 共有)
write_if_absent "$CURRENT_DIR/frontend/.env.local" "\
# Auto-generated by scripts/setup-worktree.sh
# Worktree: $WORKTREE_NAME
PORT=$FRONTEND_PORT
# Mode A (Main backend 共有): デフォルト
NEXT_PUBLIC_API_URL=http://localhost:8080
# Mode B / C (Worktree backend を使う) 場合は上をコメントアウトし、以下を有効化
# NEXT_PUBLIC_API_URL=http://localhost:$BACKEND_PORT
"

# 3. backend/.env を main からコピー (gitignoreされているため worktree には存在しない)
#    Mode B / C で worktree backend を起動するときに必要
if [ -f "$CURRENT_DIR/backend/.env" ]; then
  echo "  skip: backend/.env (既に存在)"
elif [ -f "$MAIN_REPO/backend/.env" ]; then
  cp "$MAIN_REPO/backend/.env" "$CURRENT_DIR/backend/.env"
  echo "  コピー: backend/.env (main から)"
else
  echo "  warn: main の backend/.env が見つかりません。Mode B / C を使う場合は手動で配置してください。"
fi

cat <<EOF

セットアップ完了。

▼ Mode A: フロントエンドのみ変更 (推奨・大半のケース)
   Main の backend と DB を共有するため、Docker 不要。

   cd frontend && npm install              # 初回のみ
   PORT=$FRONTEND_PORT npm run dev

   → http://localhost:$FRONTEND_PORT

   ※ Main の backend が起動済みであること:
      docker ps | grep hotaruika-bakuwaki-forecast-backend

   ※ Main の backend/.env の ALLOWED_ORIGINS に
     http://localhost:$FRONTEND_PORT が含まれていない場合は追加してください

▼ Mode B: バックエンドも変更 (Main DB を共有)
   frontend/.env.local の NEXT_PUBLIC_API_URL を
   http://localhost:$BACKEND_PORT に書き換えた上で:

   docker compose up backend --no-deps
   cd frontend && PORT=$FRONTEND_PORT npm run dev

   → Worktree backend (port $BACKEND_PORT) + Main DB (5433) を使用

▼ Mode C: DBスキーマ変更も検証
   .env の DATABASE_URL を Mode C 用に切り替え、
   frontend/.env.local の NEXT_PUBLIC_API_URL も書き換えた上で:

   docker compose up backend db
   cd frontend && PORT=$FRONTEND_PORT npm run dev

   → 完全に独立した Worktree backend (port $BACKEND_PORT) と DB (port $DB_PORT)
   → backend/sql/ のスキーマが worktree DB に自動適用される
   → DBスキーマ変更 (マイグレーション) も main に影響なく試せる
EOF
