#!/usr/bin/env bash
# Worktree用の開発環境セットアップスクリプト
#
# 使い方:
#   cd .claude/worktrees/<worktree-name>
#   bash scripts/setup-worktree.sh
#
# 動作:
#   - worktree名のハッシュから一意のポート番号を割り当て (50スロット)
#   - 使用中のポートを自動で回避
#   - .env (Compose用) と frontend/.env.local (Next.js用) を生成
#   - 通常は main の backend (port 8080) を共有して使う設定にする
#   - backend 変更時のために main の backend/.env をコピー

set -euo pipefail

# 実行場所の確認 (worktree のルートで実行されているか)
if [ ! -f "docker-compose.yml" ]; then
  echo "Error: docker-compose.yml が見つかりません。" >&2
  echo "       worktree のルートディレクトリで実行してください。" >&2
  exit 1
fi

CURRENT_DIR="$(pwd)"
WORKTREE_NAME="$(basename "$CURRENT_DIR")"

# main repo の場所を特定 (worktree の git common dir の親)
GIT_COMMON_DIR="$(git rev-parse --git-common-dir 2>/dev/null || echo "")"
if [ -z "$GIT_COMMON_DIR" ]; then
  echo "Error: git リポジトリではありません。" >&2
  exit 1
fi
MAIN_REPO="$(cd "$GIT_COMMON_DIR/.." && pwd)"

if [ "$CURRENT_DIR" = "$MAIN_REPO" ]; then
  echo "Error: このスクリプトは worktree 用です。main では実行しないでください。" >&2
  echo "       main は通常通り 'docker compose up backend db' で起動します。" >&2
  exit 1
fi

# Mac/Windows では host.docker.internal でホストのDBに接続できる
DB_HOST="host.docker.internal"
DB_URL="postgres://user:password@${DB_HOST}:5433/hotaruika_db?sslmode=disable"

# worktree名のSHA1ハッシュ先頭4桁(hex)から 1〜50 のスロット番号を計算
# Frontend port: 3100〜3149, Backend port: 8100〜8149
HASH_HEX="$(printf '%s' "$WORKTREE_NAME" | shasum | cut -c1-4)"
SLOT=$(( 16#${HASH_HEX} % 50 + 1 ))

# ポート衝突を検出して自動で次のスロットへ
MAX_TRIES=50
TRIES=0
while [ $TRIES -lt $MAX_TRIES ]; do
  FRONTEND_PORT=$((3100 + SLOT - 1))
  BACKEND_PORT=$((8100 + SLOT - 1))
  if ! lsof -iTCP:$FRONTEND_PORT -sTCP:LISTEN >/dev/null 2>&1 \
     && ! lsof -iTCP:$BACKEND_PORT -sTCP:LISTEN >/dev/null 2>&1; then
    break
  fi
  SLOT=$(( SLOT % 50 + 1 ))
  TRIES=$((TRIES + 1))
done

if [ $TRIES -ge $MAX_TRIES ]; then
  echo "Error: 空きポートが見つかりません (3100-3149 / 8100-8149 すべて使用中)" >&2
  exit 1
fi

write_if_absent() {
  local path="$1"
  local content="$2"
  if [ -f "$path" ]; then
    echo "  skip: $path (既に存在)"
  else
    printf '%s' "$content" > "$path"
    echo "  生成: $path"
  fi
}

echo ""
echo "Worktree:      $WORKTREE_NAME"
echo "スロット:      $SLOT"
echo "Frontend port: $FRONTEND_PORT"
echo "Backend port:  $BACKEND_PORT (worktree backendを起動する場合のみ使用)"
echo ""
echo "ファイル生成:"

# 1. Compose 用の .env (worktree ルート)
#    worktree backend を起動する場合のホストポート / DB接続先
#    ALLOWED_ORIGINS は backend/.env で管理 (環境ごとに変えないため)
write_if_absent "$CURRENT_DIR/.env" "\
# Auto-generated by scripts/setup-worktree.sh
# Worktree: $WORKTREE_NAME
BACKEND_PORT=$BACKEND_PORT
DATABASE_URL=$DB_URL
"

# 2. Next.js 用の .env.local
#    デフォルトで Main backend (8080) を使う設定
#    worktree backend を使いたい場合は NEXT_PUBLIC_API_URL の行を書き換える
write_if_absent "$CURRENT_DIR/frontend/.env.local" "\
# Auto-generated by scripts/setup-worktree.sh
# Worktree: $WORKTREE_NAME
PORT=$FRONTEND_PORT
# デフォルトは Main backend を共有 (Docker起動不要)
NEXT_PUBLIC_API_URL=http://localhost:8080
# worktree backend を使う場合は上の行をコメントアウトし、以下の行を有効化
# NEXT_PUBLIC_API_URL=http://localhost:$BACKEND_PORT
"

# 3. backend/.env を main からコピー (gitignoreされているため worktree には存在しない)
#    worktree backend を起動するときに必要
if [ -f "$CURRENT_DIR/backend/.env" ]; then
  echo "  skip: backend/.env (既に存在)"
elif [ -f "$MAIN_REPO/backend/.env" ]; then
  cp "$MAIN_REPO/backend/.env" "$CURRENT_DIR/backend/.env"
  echo "  コピー: backend/.env (main から)"
else
  echo "  warn: main の backend/.env が見つかりません。worktree backend を使う場合は手動で配置してください。"
fi

cat <<EOF

セットアップ完了。

▼ フロントエンドのみで動作確認する場合 (推奨)
   Main の backend と DB を共有するため、Docker 不要。

   cd frontend && npm install              # 初回のみ
   PORT=$FRONTEND_PORT npm run dev

   → http://localhost:$FRONTEND_PORT

   ※ Main の backend が起動済みであること:
      docker ps | grep hotaruika-bakuwaki-forecast-backend

   ※ Main の backend/.env の ALLOWED_ORIGINS に
     http://localhost:$FRONTEND_PORT が含まれていない場合は追加してください
     (一度設定すれば、以降の worktree でも有効)

▼ Backend の変更も検証する場合
   frontend/.env.local の NEXT_PUBLIC_API_URL を
   http://localhost:$BACKEND_PORT に書き換えた上で:

   docker compose up backend --no-deps
   cd frontend && PORT=$FRONTEND_PORT npm run dev

注意:
  - DB は main 側と共有しているため、スキーマ変更 (マイグレーション) を含む作業は
    このモードでは避けてください
EOF
