#!/usr/bin/env bash
# Worktree用の開発環境セットアップスクリプト
#
# 使い方:
#   cd .claude/worktrees/<worktree-name>
#   bash scripts/setup-worktree.sh
#
# 動作:
#   - worktree名のハッシュから一意のポート番号を割り当て
#   - .env (Compose用) と frontend/.env.local (Next.js用) を生成
#   - main の backend/.env を worktree にコピー (DBへの接続情報等)
#   - 起動コマンドを表示

set -euo pipefail

# 実行場所の確認 (worktree のルートで実行されているか)
if [ ! -f "docker-compose.yml" ]; then
  echo "Error: docker-compose.yml が見つかりません。" >&2
  echo "       worktree のルートディレクトリで実行してください。" >&2
  exit 1
fi

CURRENT_DIR="$(pwd)"
WORKTREE_NAME="$(basename "$CURRENT_DIR")"

# main repo の場所を特定 (worktree の git common dir の親)
GIT_COMMON_DIR="$(git rev-parse --git-common-dir 2>/dev/null || echo "")"
if [ -z "$GIT_COMMON_DIR" ]; then
  echo "Error: git リポジトリではありません。" >&2
  exit 1
fi
MAIN_REPO="$(cd "$GIT_COMMON_DIR/.." && pwd)"

if [ "$CURRENT_DIR" = "$MAIN_REPO" ]; then
  echo "Error: このスクリプトは worktree 用です。main では実行しないでください。" >&2
  echo "       main は通常通り 'docker compose up backend db' で起動します。" >&2
  exit 1
fi

# worktree名のSHA1ハッシュ先頭2桁(hex)を 1〜9 のスロット番号に変換
HASH_HEX="$(printf '%s' "$WORKTREE_NAME" | shasum | cut -c1-2)"
SLOT=$(( 16#${HASH_HEX} % 9 + 1 ))
BACKEND_PORT=$(( 8000 + SLOT * 100 ))     # 8100, 8200, ..., 8900
FRONTEND_PORT=$(( 3000 + SLOT * 100 ))    # 3100, 3200, ..., 3900

# Mac/Windows では host.docker.internal でホストのDBに接続できる
# Linux では --add-host=host.docker.internal:host-gateway などが必要
DB_HOST="host.docker.internal"
DB_URL="postgres://user:password@${DB_HOST}:5433/hotaruika_db?sslmode=disable"

write_if_absent() {
  local path="$1"
  local content="$2"
  if [ -f "$path" ]; then
    echo "  skip: $path (既に存在)"
  else
    printf '%s' "$content" > "$path"
    echo "  生成: $path"
  fi
}

echo ""
echo "Worktree:     $WORKTREE_NAME"
echo "スロット:     $SLOT"
echo "Backend port: $BACKEND_PORT"
echo "Frontend port: $FRONTEND_PORT"
echo ""
echo "ファイル生成:"

# 1. Compose 用の .env (worktree ルート)
write_if_absent "$CURRENT_DIR/.env" "\
# Auto-generated by scripts/setup-worktree.sh
# Worktree: $WORKTREE_NAME
BACKEND_PORT=$BACKEND_PORT
DATABASE_URL=$DB_URL
ALLOWED_ORIGINS=http://localhost:$FRONTEND_PORT
"

# 2. Next.js 用の .env.local
write_if_absent "$CURRENT_DIR/frontend/.env.local" "\
# Auto-generated by scripts/setup-worktree.sh
# Worktree: $WORKTREE_NAME
PORT=$FRONTEND_PORT
NEXT_PUBLIC_API_BASE_URL=http://localhost:$BACKEND_PORT
"

# 3. backend/.env を main からコピー (gitignoreされているため worktree には存在しない)
if [ -f "$CURRENT_DIR/backend/.env" ]; then
  echo "  skip: backend/.env (既に存在)"
elif [ -f "$MAIN_REPO/backend/.env" ]; then
  cp "$MAIN_REPO/backend/.env" "$CURRENT_DIR/backend/.env"
  echo "  コピー: backend/.env (main から)"
else
  echo "  warn: main の backend/.env が見つかりません。手動で配置してください。"
fi

cat <<EOF

セットアップ完了。起動コマンド:

  # backend (DB は main 側を共有するので --no-deps)
  docker compose up backend --no-deps

  # frontend (別タブで)
  cd frontend && npm run dev

  → frontend: http://localhost:$FRONTEND_PORT
  → backend:  http://localhost:$BACKEND_PORT

注意:
  - main の DB コンテナ (port 5433) が起動している必要があります
  - スキーマ変更 (マイグレーション) を含む作業はこのモードでは避けてください
    (main の DB を直接書き換えてしまうため)
EOF
